In [1]:
import numpy as np

In [2]:
type(np.array(["vnvhv",2,3]))

numpy.ndarray

In [3]:
lst = [1,2,3]
type(lst)

list

In [6]:
a = np.array(lst)
a

array([1, 2, 3])

In [7]:
a.shape

(3,)

In [35]:
lst = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
a = np.array(lst)

In [36]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
a.shape

(4, 3)

In [38]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [39]:
np.array([1,2,3],ndmin = 5)

array([[[[[1, 2, 3]]]]])

In [40]:
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [41]:
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [42]:
np.array([1,2,3],dtype = np.float32)

array([1., 2., 3.], dtype=float32)

In [43]:
a[2][2]

9

In [44]:
a[1:3,:2]

array([[4, 5],
       [7, 8]])

In [45]:
a[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [46]:
a[1:3,[0,2]]

array([[4, 6],
       [7, 9]])

In [56]:
a[[0,3]][:,[0,2]]

array([[ 1,  3],
       [10, 12]])

In [58]:
ma = np.mat(np.array([[1,2],[3,4]]))

In [59]:
ma.T

matrix([[1, 3],
        [2, 4]])

In [60]:
a.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [72]:
arr1 = np.array([1,2,3])
arr2 = np.asarray([1,2,3])

In [73]:
arr1 is arr2

False

In [74]:
#######np from function######

In [80]:
a = lambda i,j: i==j


In [81]:
np.fromfunction(lambda i,j: i==j, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])