In [10]:
### WEB APIs ###
import pandas as pd

In [2]:
import requests
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
resp = requests.get(url)
resp

C:\ProgramData\Anaconda3\lib\site-packages\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "


<Response [200]>

In [3]:
data = resp.json()

In [8]:
(data[2]['user'])

{'login': 'AlexKirko',
 'id': 23253999,
 'node_id': 'MDQ6VXNlcjIzMjUzOTk5',
 'avatar_url': 'https://avatars.githubusercontent.com/u/23253999?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/AlexKirko',
 'html_url': 'https://github.com/AlexKirko',
 'followers_url': 'https://api.github.com/users/AlexKirko/followers',
 'following_url': 'https://api.github.com/users/AlexKirko/following{/other_user}',
 'gists_url': 'https://api.github.com/users/AlexKirko/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/AlexKirko/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/AlexKirko/subscriptions',
 'organizations_url': 'https://api.github.com/users/AlexKirko/orgs',
 'repos_url': 'https://api.github.com/users/AlexKirko/repos',
 'events_url': 'https://api.github.com/users/AlexKirko/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/AlexKirko/received_events',
 'type': 'User',
 'site_admin': False}

In [18]:
data[0]['comments_url']

'https://api.github.com/repos/pandas-dev/pandas/issues/40137/comments'

In [19]:
data[0]['user']

{'login': 'simonjayhawkins',
 'id': 13159005,
 'node_id': 'MDQ6VXNlcjEzMTU5MDA1',
 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/simonjayhawkins',
 'html_url': 'https://github.com/simonjayhawkins',
 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',
 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',
 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',
 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',
 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',
 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_even

In [21]:
issues = pd.DataFrame(data, columns=['number','title','labels','state'])
issues.head()

number                                              title  \
0   40137                            DOC: 1.2.3 release date   
1   40136           ⬆️ UPGRADE: Autoupdate pre-commit config   
2   40135               WIP: ENH: Support ZoneInfo timezones   
3   40134  DEPR: `Styler.set_na_rep` and `.set_precision`...   
4   40133    TST: collect tests by method, split large tests   

                                              labels state  
0  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
1                                                 []  open  
2                                                 []  open  
3                                                 []  open  
4                                                 []  open

In [22]:
### Interacting with databases ###

In [23]:
### sqlite (mobile phones---2GB)

In [28]:
import sqlite3
#connecting with the databases
con = sqlite3.connect('mydata2.sqlite')
# drop table if it already exits using excecute() method.
con.execute("drop table if exists test")
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),c REAL,d INTEGER
);
"""
con.execute(query)
con.commit()

In [30]:
data = [('atlanta','geo',1.25,6),
       ('atlanta','geo',1.90,7),
       ('atlanta','geo',1.80,4)]
stmt = "INSERT INTO test VALUES(?,?,?,?)"
con.executemany(stmt, data)
con.commit()

In [35]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('atlanta', 'geo', 1.25, 6),
 ('atlanta', 'geo', 1.9, 7),
 ('atlanta', 'geo', 1.8, 4)]

In [40]:
cursor.description[0]

('a', None, None, None, None, None, None)

In [43]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

a    b     c  d
0  atlanta  geo  1.25  6
1  atlanta  geo  1.90  7
2  atlanta  geo  1.80  4

## Pandas data Manipulation

In [44]:
import pandas as np
import numpy as np
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [47]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/fa71405126017e6a37bea592440b4bee94bf7b9e/titanic.csv")
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [76]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [77]:
titanic_train.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [88]:
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index

In [91]:
titanic_train[a].describeribe()

Name   Sex    Ticket Cabin Embarked
count                             891   891       891   204      889
unique                            891     2       681   147        3
top     Bourke, Mrs. John (Catherine)  male  CA. 2343    G6        S
freq                                1   577         7     4      644

In [94]:
titanic_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [97]:
titanic_train[["Name","Age"]]

Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [106]:
sorted(titanic_train["Name"])[5:10:2]

['Adahl, Mr. Mauritz Nils Martin',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Albimona, Mr. Nassef Cassem']

In [109]:
titanic_train["Pclass"].unique()

array([3, 1, 2], dtype=int64)

In [110]:
pd.Categorical(titanic_train["Pclass"])

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [113]:
titanic_train["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [115]:
titanic_train.info() #cabin

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [117]:
char_cabin = titanic_train["Cabin"].astype(str)

In [121]:
new_cabin = [x[0] for x in char_cabin]
new_cabin = pd.Categorical(new_cabin)

In [122]:
new_cabin

['n', 'C', 'n', 'C', 'n', ..., 'n', 'B', 'n', 'C', 'n']
Length: 891
Categories (9, object): ['A', 'B', 'C', 'D', ..., 'F', 'G', 'T', 'n']

In [124]:
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [ ]:
## krish naik machine learning playlist
## livestream playlist of krish